apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-qdca10pro
  description: "quarkusdroneshop-qdca10pro のドリンク製造マイクロサービスです（プロ版）"
  tags:
    - latest
    - b-cluster
  labels:
    app: qdca10pro
  annotations:
    github.com/project-slug: quarkusdroneshop/quarkusdroneshop-qdca10pro
    backstage.io/kubernetes-id: quarkusdroneshop-qdca10pro
    backstage.io/kubernetes-cluster: b-cluster
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=quarkusdroneshop-qdca10pro
    argocd/app-selector: app.kubernetes.io/instance=quarkusdroneshop-qdca10pro
    tekton.dev/cicd: "true"
    tekton.dev/type: pipeline
    tektonci.io/pipeline: build-and-push-quarkusdroneshop-qdca10pro
    tektonci.io/pipelineNamespace: quarkusdroneshop-cicd
    janus-idp.io/tekton: "true"
    rhdh.redhat.com/tekton-enabled: "true"
    backstage.io/techdocs-ref: dir:.
spec:
  type: microservice
  lifecycle: production
  owner: user:default/nmushino
  system: b-cluster
  dependsOn:
    - resource:shop-cluster-kafka-bsite
    - resource:shop-bsite-qdca10pro-in
    - resource:droneshopdb-bsite-postgresql
  consumesApis:
    - kafka-bsite-qdca10pro-in
  providesApis:
    - kafka-bsite-orders-up
    - kafka-bsite-eighty-six
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kafka-bsite-qdca10pro-in
  description: "Kafka トピック: shop-asite.qdca10pro-in（QDCA10Pro注文チケット受信）"
  annotations:
    backstage.io/kubernetes-cluster: b-cluster
    openmetadata/explore-url: "http://openmetadata-openmetadata.apps.ocp.7n8gs.sandbox847.opentlc.com/topic/external-shop-cluster-kafka-bsite%3A9094.qdca10pro-in/schema"
  links:
    - url: "http://openmetadata-openmetadata.apps.ocp.7n8gs.sandbox847.opentlc.com/topic/external-shop-cluster-kafka-bsite%3A9094.qdca10pro-in/schema"
      title: データカタログ
      icon: dashboard
spec:
  type: asyncapi
  lifecycle: production
  owner: user:default/nmushino
  system: b-cluster
  definition: |
    asyncapi: 2.6.0
    info:
      title: shop-asite.qdca10pro-in
      version: 1.0.0
      description: QDCA10Proが注文チケットを受信するトピック
    servers:
      production:
        url: shop-cluster-kafka-bootstrap:9092
        protocol: kafka
    channels:
      shop-asite.qdca10pro-in:
        description: QDCA10Proへの注文チケットを受信するトピック
        subscribe:
          operationId: receiveQdca10proOrder
          message:
            name: OrderTicket
            contentType: application/json
            payload:
              type: object
              properties:
                orderId:
                  type: string
                item:
                  type: string
                preparedBy:
                  type: string
