apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-qdca10pro
  description: "quarkusdroneshop-qdca10pro のドリンク製造マイクロサービスです（プレミアム）"
  tags:
    - latest
    - b-cluster
  labels:
    app: qdca10pro
  annotations:
    backstage.io/kubernetes-id: quarkusdroneshop-qdca10pro
    backstage.io/kubernetes-cluster: b-cluster
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=quarkusdroneshop-qdca10pro
    argocd/app-selector: app.kubernetes.io/instance=quarkusdroneshop-qdca10pro
    tektonci.io/pipeline: build-and-push-quarkusdroneshop-qdca10pro
    tektonci.io/pipelineNamespace: quarkusdroneshop-cicd
    tekton.dev/type: pipeline
    tekton.dev/cicd: "true"
    janus-idp.io/tekton: "true"
    rhdh.redhat.com/tekton-enabled: "true"
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: user:default/nmushino
  system: b-cluster
  dependsOn:
    - resource:shop-cluster-kafka
    - resource:shop-bsite-qdca10pro-in
    - resource:droneshopdb-bsite-postgresql
  consumesApis:
    - kafka-bsite-qdca10pro-in
  providesApis:
    - kafka-bsite-orders-up
