apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-qdca10pro
  description: QDCA10Proシリーズのマイクロサービスです
  tags:
    - latest
    - b-cluster
  labels:
    app: qdca10pro
  annotations:
    github.com/project-slug: quarkusdroneshop/qdca10
    backstage.io/kubernetes-id: quarkusdroneshop-qdca10pro
    backstage.io/kubernetes-cluster: b-cluster
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=qdca10pro
spec:
  type: microservice
  owner: user:default/nmushino
  lifecycle: production
  system: b-cluster
  dependsOn:
    - resource:shop-cluster-kafka
    - resource:shop-asite-qdca10pro-in
  consumesApis:
    - kafka-shop-asite-qdca10pro-in
  providesApis:
    - kafka-orders-up
    - kafka-eighty-six
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kafka-shop-asite-qdca10pro-in
  description: "Kafka トピック: shop-asite.qdca10pro-in（QDCA10Pro注文チケット受信）"
  annotations:
    backstage.io/kubernetes-cluster: b-cluster
spec:
  type: asyncapi
  lifecycle: production
  owner: user:default/nmushino
  system: b-cluster
  definition: |
    asyncapi: 2.6.0
    info:
      title: shop-asite.qdca10pro-in
      version: 1.0.0
      description: QDCA10Proが注文チケットを受信するトピック
    servers:
      production:
        url: shop-cluster-kafka-bootstrap:9092
        protocol: kafka
    channels:
      shop-asite.qdca10pro-in:
        description: QDCA10Proへの注文チケットを受信するトピック
        subscribe:
          operationId: receiveQdca10proOrder
          message:
            name: OrderTicket
            contentType: application/json
            payload:
              type: object
              properties:
                orderId:
                  type: string
                item:
                  type: string
                preparedBy:
                  type: string
